services:
  caddy:
    image: caddy:2-alpine
    container_name: chatter_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data # SSL certs
      - caddy_config:/config
    depends_on:
      server:
        condition: service_started
    networks:
      - frontend

  db:
    image: postgres:18-alpine
    container_name: chatter_db
    restart: always
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d chatter
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # nats:
  #   image: nats:alpine
  #   container_name: chatter_broker
  #   restart: always
  #   command: --user ${NATS_USER} --pass ${NATS_PASSWORD} -js -m 8222 -sd /data
  #   ports:
  #     - "4222:4222"
  #     - "8222:8222"
  #   volumes:
  #     - nats_data:/data
  #   healthcheck:
  #     test: wget --spider -q http://localhost:8222/healthz
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  server:
    image: scanning5/chatter-server:latest
    container_name: chatter_app
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
      # nats:
      #   condition: service_healthy
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  frontend:
  backend:
